### PR TITLE
Add error message, options parameter and Update README

### PR DESCRIPTION
**Pull request by Sporarum**

### CODE REVIEW

**Comment by jad-hamza** [comment]
Thanks! It looks like you only fetch the executable path and the options once? What do you think about moving that in the executions of the commands?

**Comment by Sporarum** [comment]
Oh yeah, I can do that, I'll refactor it into function calls

**Comment by Sporarum** [comment]
Finally done, sorry for the delay

**Comment by jad-hamza** [comment]
Merged, thanks!

**Pull request merged**
